// The skill package and plugin (authoring-skill spec, design D8, D11). The first test rebuilds, so the others
// check a fresh build.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { copyFileSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { unzipSync } from 'fflate';
import { readFolder } from './helpers.js';
import { PRIVATE_NAMES } from '../private-names.js';

const ROOT = fileURLToPath(new URL('../../', import.meta.url));
const SKILL = join(ROOT, 'skills/operating-model-author');
const read = (p) => readFileSync(join(ROOT, p), 'utf8');
const node = (args, cwd = ROOT) => spawnSync(process.execPath, args, { cwd, encoding: 'utf8' });
const hashes = (dir) => Object.fromEntries(readFolder(dir).map((f) => [f.path, createHash('sha256').update(f.data).digest('hex')]));
const REFERENCES = ['capture-sheet-format.md', 'capture-sheet-template.md', 'example-capture-sheet.md', 'interview-guide.md'];

test('2.50 committed skill folder is current: a build changes nothing under skills/ or .claude-plugin/', () => {
  const before = [hashes(SKILL), hashes(join(ROOT, '.claude-plugin'))];
  const r = node(['scripts/build.mjs']);
  assert.equal(r.status, 0, r.stderr);
  assert.deepEqual([hashes(SKILL), hashes(join(ROOT, '.claude-plugin'))], before, 'run npm run build and commit the skill folder');
});

test('2.19 package contents: the zip holds SKILL.md, the four references, the validator and the matching engine', () => {
  const zip = unzipSync(readFileSync(join(ROOT, 'dist/operating-model-author.zip')));
  const names = Object.keys(zip).map((p) => p.replace(/^operating-model-author\//, '')).sort();
  assert.deepEqual(names, ['SKILL.md', 'engine/operating-model-explorer.html', ...REFERENCES.map((r) => `references/${r}`), ...['acme', 'globex'].flatMap((b) => [`references/brands/${b}/brand.md`, `references/brands/${b}/mark.svg`]), 'scripts/validate.mjs'].sort());
  // The zip is the committed folder, and its engine is the standalone engine, byte for byte (1.19).
  for (const [p, data] of Object.entries(zip)) assert.ok(Buffer.from(data).equals(readFileSync(join(ROOT, 'skills', p))), p);
  assert.ok(Buffer.from(zip['operating-model-author/engine/operating-model-explorer.html']).equals(readFileSync(join(ROOT, 'dist/operating-model-explorer.html'))));
  const sums = read('dist/SHA256SUMS');
  for (const f of ['operating-model-author.zip', 'operating-model-explorer.html']) {
    assert.match(sums, new RegExp(`^${createHash('sha256').update(readFileSync(join(ROOT, 'dist', f))).digest('hex')}  ${f.replace('.', '\\.')}$`, 'm'));
  }
});

test('2.20 bundled validator runs on its own: copied into an empty folder, 0 errors and 0 warnings on the Acme sheet', () => {
  const zip = unzipSync(readFileSync(join(ROOT, 'dist/operating-model-author.zip')));
  const out = mkdtempSync(join(tmpdir(), 'om-skill-'));
  for (const [p, data] of Object.entries(zip)) {
    mkdirSync(dirname(join(out, 'unzipped', p)), { recursive: true });
    writeFileSync(join(out, 'unzipped', p), data);
  }
  const empty = join(out, 'empty');
  mkdirSync(empty);
  copyFileSync(join(out, 'unzipped/operating-model-author/scripts/validate.mjs'), join(empty, 'validate.mjs'));
  const r = node(['validate.mjs', join(out, 'unzipped/operating-model-author/references/example-capture-sheet.md')], empty);
  assert.equal(r.stdout.trim().split('\n').at(-1), '0 errors, 0 warnings', r.stdout + r.stderr);
  assert.equal(r.status, 0);
  const bad = node(['validate.mjs', join(ROOT, 'tests/fixtures/sheet-unknown-owner/capture-sheet.md')], empty);
  assert.equal(bad.status, 1, 'errors still fail the bundled validator');
});

test('references are the core files plus a "generated" note, and still read as the same sheet', () => {
  const sources = ['docs/capture-sheet.md', 'templates/capture-sheet.md', 'examples/acme-capture-sheet/capture-sheet.md', 'docs/interview-guide.md'];
  REFERENCES.forEach((r, i) => assert.equal(read(`skills/operating-model-author/references/${r}`), `<!-- Generated by npm run build from ${sources[i]}. Do not edit this copy; edit the source. -->\n\n${read(sources[i])}`));
});

test('2.21 core has no Claude-specific content: the four references name no assistant, tool or command', () => {
  const claudeSpecific = /\b(claude|anthropic|skill\.md|askuserquestion|todowrite|subagent|slash command|tool call|mcp|plugin)\b|\b(Bash|Glob|Grep)\b|\/(plugin|opsx)\b/i;
  for (const r of REFERENCES) {
    const text = readFileSync(join(SKILL, 'references', r), 'utf8');
    assert.doesNotMatch(text, claudeSpecific, r);
  }
});

test('1.18 plugin manifests: marketplace operating-model-explorer lists plugin operating-model-author from the repo root', () => {
  const market = JSON.parse(read('.claude-plugin/marketplace.json'));
  const plugin = JSON.parse(read('.claude-plugin/plugin.json'));
  assert.equal(market.name, 'operating-model-explorer');
  assert.deepEqual(market.plugins.map((p) => [p.name, p.source]), [['operating-model-author', './']]);
  assert.equal(plugin.name, 'operating-model-author');
  // Claude Code finds the plugin's skills in skills/<name>/SKILL.md; the skill carries the plugin's name.
  assert.match(read('skills/operating-model-author/SKILL.md'), /^---\nname: operating-model-author\ndescription: >\n/);
});

test('the skill folder, the trial packs and the planning docs (openspec/) contain no real company names', () => {
  if (!PRIVATE_NAMES) return;
  for (const dir of ['skills', 'tests/skill-packs', '.claude-plugin', 'openspec']) {
    for (const f of readFolder(join(ROOT, dir))) assert.doesNotMatch(new TextDecoder().decode(f.data), PRIVATE_NAMES, `${dir}/${f.path}`);
  }
});

test('the trial packs are all there', () => {
  const packs = readdirSync(join(ROOT, 'tests/skill-packs'), { withFileTypes: true }).filter((e) => e.isDirectory()).map((e) => e.name).sort();
  assert.deepEqual(packs, ['brand-library', 'contradictions', 'org-chart', 'revision', 'rich', 'thin']);
  assert.match(read('tests/skill-packs/contradictions/raci-table.md'), /\| Capture the lead \| A\/R \|/);
});
